### ISSUE TITLE
Researching potential API validation libraries (compatible with Stoplight)

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1829]

**Comment by kuzdogan** [comment]
Upon a seach, I couldn't really find a better or more popular alternative. `express-openapi-validator` has been working decently for us anyway. 

The only question I have now is it will accommodate our schema/format definitions in the v2 spec. Namely, in our legacy API we define `format`s:
```ts
        formats: {
          "comma-separated-addresses": {
            type: "string",
            validate: (addresses: string) => validateAddresses(addresses),
          },
          address: {
            type: "string",
            validate: (address: string) => validateSingleAddress(address),
          },
```

and these are then referred in the OpenAPI spec as such:
```yaml
paths:
  /check-all-by-addresses:
    get:
      ...
      parameters:
        - name: addresses
          in: query
          description: Comma seperated string of addresses to check for.
          required: true
          schema:
            type: string
            format: comma-separated-addresses
```

Whereas the v2 spec defines a `schema` for parameters:
```yaml
parameters:
    address:
      name: address
      in: path
      description: Contract's 20 byte address in hex string with the 0x prefix. Case insensitive.
      required: true
      schema:
        type: string
        pattern: '(\b0x[a-fA-F0-9]{40}\b)'
        minLength: 42
        maxLength: 42
        examples:
          - '0x2738d13E81e30bC615766A0410e7cF199FD59A83'
```

and then
```yaml
    VerifiedContractMinimal:
      type: object
      title: VerifiedContractMinimal
      properties:
        address:
          $ref: '#/components/schemas/Address'
```

My guess would be yes but that's something to keep double check while implementing.

Closing the issue but adding this as to #1367
